spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tododetails?useSSL=false
    username: root
    password: Root

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
